Project based learning, mengenal data science dari awal (pake bantuan gemini sih)

In [4]:
import pandas as pd 

df = pd.read_csv('tesdata1.csv', sep=';')

df.head(5)

      nama  nilai  jam_bljr lulus
0   Soraya  100.0      15.0     y
1   Amalia   95.0      10.0     y
2  Fulanah   65.0       4.0     y
3  Fulanah   80.0       4.0     y
4     Ruby   40.0       1.0     n

In [5]:
df.describe()

            nilai   jam_bljr
count    5.000000   5.000000
mean    76.000000   6.800000
std     24.341323   5.630275
min     40.000000   1.000000
25%     65.000000   4.000000
50%     80.000000   4.000000
75%     95.000000  10.000000
max    100.000000  15.000000

In [9]:
df = df.drop_duplicates(subset=['nama'], keep='first')

df['Kategori_siswa'] = df['jam_bljr'].apply(lambda x: 'Rajin' if x >= 8 else 'Biasa')

df.head()

      nama  nilai  jam_bljr lulus Kategori_siswa
0   Soraya  100.0      15.0     y          Rajin
1   Amalia   95.0      10.0     y          Rajin
2  Fulanah   65.0       4.0     y          Biasa
4     Ruby   40.0       1.0     n          Biasa
5      NaN    NaN       NaN   NaN          Biasa