Read Dataset

In [2]:
import pandas as pd 

df_raw = pd.read_csv('cafe_kalsel.csv')
df_raw.head(5)

,OSrXXb,rllt__details,yi40Hd,RDApEe,rllt__details 2,ncRHuf,r3PLsf,ncRHuf 2,wA1Bge src,r3PLsf 2,ncRHuf 3,rllt__details 3,rllt__details 4
0,Titik tenang coffee,· Coffee shop,"4,8",(46),"Banjarmasin City, South Kalimantan",Dine-in,·,Takeaway,https://lh3.googleusercontent.com/gps-cs-s/AHR...,NaN,NaN,NaN,NaN
1,miracle.coffeee,· Coffee shop,"4,6",(287),"Banjarmasin City, South Kalimantan",Dine-in,·,Takeaway,https://lh3.googleusercontent.com/gps-cs-s/AHR...,·,No-contact delivery,NaN,NaN
2,Mi.u Coffee,· Coffee shop,"5,0",(29),"Banjarmasin City, South Kalimantan",Dine-in,·,Drive-through,https://lh3.googleusercontent.com/gps-cs-s/AHR...,·,Delivery,NaN,NaN
3,Spaceground Coffee and Eatery,· Coffee shop,"4,6",(284),"Banjarmasin City, South Kalimantan",Dine-in,·,Takeaway,https://lh3.googleusercontent.com/gps-cs-s/AHR...,·,Delivery,NaN,NaN
4,Golden Brew,· Coffee shop,"4,4",(361),"Banjarmasin City, South Kalimantan",Dine-in,·,Takeaway,https://lh3.googleusercontent.com/gps-cs-s/AHR...,NaN,NaN,NaN,NaN

Ganti nama kolom

In [3]:
df = df_raw[
    ['OSrXXb', 'rllt__details', 'rllt__details 2', 'ncRHuf', 'wA1Bge src']].rename(
    columns={
        'OSrXXb' : "nama_cafe",
        'rllt__details' : "kategori",
        'rllt__details 2' : "kota_prov",
        'ncRHuf' : "bisa_dinein",
        'wA1Bge src' : "link_gmaps"
    }
)

Memilah kategori

In [4]:
df['kategori'] = (df['kategori'].astype(str).str.replace('· ', '').str.strip())

df = df[
    df['kategori'].str.contains('cafe|coffee|bakery', case=False, na=False)
]

Simpan yang kota nya jelas

In [5]:
df = df[
    df['kota_prov'].str.contains('kalimantan|city', case=False, na=False)
]

pd.set_option('display.max_rows', None)

df

,nama_cafe,kategori,kota_prov,bisa_dinein,link_gmaps
0,Titik tenang coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
1,miracle.coffeee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
2,Mi.u Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
3,Spaceground Coffee and Eatery,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
4,Golden Brew,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
5,LaMajesty Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
6,Kubiek Coffee and Eatery,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
7,DJF Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
8,101 COFFEE (KM.5 SLM),Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
9,Kopi 1815,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
10,Koelacino,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
11,Monslay Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
12,Pamera Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
13,GENJI COFFEE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
14,KUBIEK COFFEE HOUSE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
15,New Goodwill Coffee and Eatery,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
16,Commonsense Coffee and Roastery,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
17,MNML coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
19,GAS COFFEE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
20,Pasaraya Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
21,Neir Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
22,"Hello Coffee,Bakery & Brunch",Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
23,ARUNIKA COFFEE AND SPACE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
24,Kopi MAE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
25,Jungle Coffee Bar,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
26,Cangkir Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
27,JINAK X LRDBY BANJARMASIN,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
28,Tradisi Kopi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
29,KOPI AVA & CAFE BERINGIN,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
30,Universe Coffee banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
31,0 Km Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
32,AOS street coffe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
33,Sekalimantan.coffee,Coffee shop,"Banjarbaru City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
34,Boemi Aroma Kopitiam & Roastery,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
35,sikusiku coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
36,Hukai Coffee,Coffee shop,"Banjar Regency, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
37,Panen Hijau,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
38,KIWA KOFFIE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
39,Serdadu Coffe And Space,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
40,Teras Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
41,Sepuluh.11,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
42,Sixth Sense Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
43,Duduk Sini Koffie,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
44,Office Coffee Headquarter,Coffee shop,"Banjarmasin City, South Kalimantan",NaN,https://lh3.googleusercontent.com/gps-cs-s/AHR...
45,97 Degree Coffee,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
47,Hanpis Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",NaN,https://lh3.googleusercontent.com/gps-cs-s/AHR...
48,Nango Kopi,Cafe,"Kalimantan Selatan, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
49,Kedaikopiopung,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
50,Marina Kopi,Coffee shop,"Banjar Regency, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
51,AWAK COFFEE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
52,Hana Coffee (Street Coffee),Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
53,Fika Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
54,Toko kopi muara raya,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
55,DAN COFFEE HOUSE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
56,Kisah Kita Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
57,Nismara,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
58,Timur Jauh,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
59,De'Kopi Arwana,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
60,Fifty Two Brew House Sidelines,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
61,Oshe Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
62,A Thousand Feet for Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
63,Teman Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
64,Kopi Gatsu,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
65,Kise Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
66,Muara Coffee and Space,Coffee shop,"Banjarbaru City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
67,Siklus Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
68,Ambin Kopi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
69,81 Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
70,Nordu Coffee Capung Banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
71,E.xkopi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
72,101 COFFEE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
73,KOHY COFFEE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
74,FOOTSTEP COFFEE,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
75,Greeting.co (Coffee & Creamy),Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
76,Tepi Jalan Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
77,The Efa Cafe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
78,Twin Koffie,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
79,Hulu Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
80,Bluebell Coffeeshop,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
81,The Garden Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
82,Kosakata Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
83,Lingkaran malam coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
84,Sunny Coffee & Croissant Banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
86,SOG Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
87,TOKO SOEDIMAMPIR COFFEE.LAB,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
88,KAMPOENG ARAB COFFEE HOUSE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
89,Nordu Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
90,Kedai bobacin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
91,William Baked,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
92,Kampus Wisdom Secangkir kopi seribu inspirasi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
93,Coffe Harapan,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
94,Kopi Ruang hati gunsar,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
96,Effronte,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
97,Maja Bakehouse,Bakery,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
98,Issho Coffee - Banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
99,Earth Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
100,Coffee Toffee - Taher Square,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
101,Area koffie,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
102,LUNAR COFFEE AND PIZZA,Coffee shop,"Barito Kuala Regency, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
103,Eatme X Coffeebeats,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
104,Kedai Kopi / Coffee Shop Green Beans Banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
105,Moji Kopi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
106,Kawai Kofie,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
107,SIMETRIS KOFFIE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
108,Kupi Angkai Banjarmasin ex. Kong Djie Coffee B...,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
109,Kopingin.beverages,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
110,AIUEO CAFE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
112,DE VILLAGE CAFE,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
113,KING RESERVE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
114,KOTALAMA KOFFIE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
115,Stay With Me.,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
116,Toko kopi Marantika,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/webp;base64,UklGRqAFAABXRUJQVlA4IJQ..."
117,Kedai Kopi Koffeeahh,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
118,"BIVIO Coffe,pastry,eatery",Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
119,.urbane coffe roaster,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
120,by.us Coffe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
121,Kopi Perjalanan,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://www.google.com/maps/vt/data=epOls2VAU8...
122,Nauli Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
123,Fhase,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
124,Kopi Minan,Coffee shop,"Banjar Regency, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
125,Cafe Nostalgia,Cafe,"Banjarmasin City, South Kalimantan",Takeaway,https://lh3.googleusercontent.com/gps-cs-s/AHR...
126,Lantai Satu Coffe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
127,SANDHYAKALA COFFEE & COOKIE,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
128,102 banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://www.google.com/maps/vt/data=IUVOKL_h-p...
129,Aracha Coffee & Matcha,Coffee shop,"Barito Kuala Regency, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
130,Kala Cafe BDJ - 02 (Adhyaksa),Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
131,Cafe California,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
132,Delapan Dua Coffee,Cafe,"Banjarmasin City, South Kalimantan",NaN,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
133,KumpulSantai kopi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
134,Seadanya Koffie,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
135,Nobis Coffee,Coffee shop,"Barito Kuala Regency, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
136,Toko Kopi Utara,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/webp;base64,UklGRm4GAABXRUJQVlA4IGI..."
137,Excelso Pal 5.5 Banjarmasin,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
138,Kopi Konnichiwa X Tokyo Gorilla Pegadaian Banj...,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
139,Mom's Bakery & Cafe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
140,Cafe Ouds,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://www.google.com/maps/vt/data=sSaycAi6uF...
141,Larry's Coffee,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
142,MRK Coffee & Aspirations,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
143,Enchante Bistro & Cafe,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
144,Point Coffee Jafri Zam Zam,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
145,1960 Coffee,Coffee shop,"Banjarbaru City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
146,De' Paola coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
147,5054 caffe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://www.google.com/maps/vt/data=RuGHDAweS9...
148,Umah Lou Cafe,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
149,Jitterbug Coffee & Warung Mobil - Banjarbaru,Coffee shop,"Banjarbaru City, South Kalimantan",Dine-in,https://lh3.googleusercontent.com/gps-cs-s/AHR...
150,Kedai Kopi Cangkal,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
151,Moana Bakehouse,Bakery,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
152,Sabar Menanti Coffee Roaster Banjarmasin,Cafe,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
153,Fore Coffee - Duta Mall Banjarmasin,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
154,Setara.,Coffee shop,"Banjarbaru City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
155,4 Titik Kopi,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
156,Cappuccino Sinchan,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/webp;base64,UklGRsADAABXRUJQVlA4ILQ..."
157,CAFEIN (Coffee and Studio),Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
158,Pelataran Coffee,Coffee shop,"Banjarmasin City, South Kalimantan",Dine-in,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."